---
title: "IEEE-754 浮点数"
---

$V=(-1)^s \times M \times 2^E$

- 符号（sign）：$s$
- 尾数（mantissa）：$M$ 是一个二进制小数，范围是 $1 \sim 2-\varepsilon$（规格化）或 $0 \sim 1-\varepsilon$（非规格化）
- 阶码（exponent）：$E$ 对浮点数加权

浮点数的格式：

- `float`：$1$ 位的 `s`，$8$ 位的 `exp`，$23$ 位的 `frac`
- `double`：$1$ 位的 `s`，$11$ 位的 `exp`，$52$ 位的 `frac`

浮点数的值：

- 规格化的值：**当 `exp` 既不是全 $0$，也不是全 $1$ 时**。阶码值 $E=e-\text{Bias}$。小数字段 `frac` 为二进制小数 $f=0.f_{n-1}\cdots f_1f_0$ 的值，尾数 $M=f+1$（隐含的以 1 开头表示，白得一个额外的精度位）

  - $\text{Bias}=2^{k-1}-1$（单精度 $k=8, \text{Bias}=127$，双精度 $k=11, \text{Bias}=1023$）。

  - $E$ 的范围 $-126\sim 127$ 或 $-1022\sim 1023$。

- 非规格化的值：**当阶码域 `exp` 全 $0$ 时**。阶码值 $E=1-\text{Bias}$，尾数 $M=f$，不包含隐含的 1.
- 特殊值：**当阶码全为 $1$ 时**。若小数域全 $0$，则得到 $+\infin$ 或 $-\infin$，否则得到 NaN.

***

为什么要有非规格化的值？规格化的值无法表示 $0.0$，以及 $0$ 附近的极小值。引入非规格化的值可以平滑地表示 $+0.0$、$-0.0$ 以及非常接近于 $0$ 的数（gradual underflow）。

为什么要去掉尾数中的隐含 $1$？为了表示 $0.0$ 以及 $0.0$ 附近的数。

为什么要特别令阶码 $E=1-\text{Bias}$，而不是直接取 $E=-\text{Bias}$？为了过渡更平滑。

***

浮点数的范围：
| 描述 | `exp` | `frac` | 单精度值 | 双精度值 |
| :------------: | :-----------: | :-----------: | :-------------------------------------------------: | :---------------------------------------------------: |
| 0 | $00\cdots 00$ | $00\cdots 00$ | $0.0$ | $0.0$ |
| 最小非规格化数 | $00\cdots 00$ | $00\cdots 01$ | $2^{-23}\times 2^{-126}=1.4\times 10^{-45}$ | $2^{-52}\times 2^{-1022}=4.9\times 10^{-324}$ |
| 最大非规格化数 | $00\cdots 00$ | $11\cdots 11$ | $(1-\varepsilon)\times 2^{-126}=1.2\times 10^{-38}$ | $(1-\varepsilon)\times 2^{-1022}=2.2\times 10^{-308}$ |
| 最小规格化数 | $00\cdots 01$ | $00\cdots 00$ | $1.0\times 2^{-126}=1.2\times 10^{-38}$ | $1.0\times 2^{-1022}=2.2\times 10^{-308}$ |
| 1 | $01\cdots 11$ | $00\cdots 00$ | $1.0$ | $1.0$ |
| 最大规格化数 | $11\cdots 10$ | $11\cdots 11$ | $(2-\varepsilon)\times 2^{127}=3.4\times 10^{38}$ | $(2-\varepsilon)\times 2^{1023}=1.8\times 10^{308}$ |

***

$12345$ 具有二进制表示 $11000000111001$，小数点左移 $13$ 位得 $1.1000000111001_2 \times 2^{13}$，丢弃开头的 $1$ ，并在末尾添加 $10$ 个 $0$，得小数字段 $[10000001110010000000000]$。阶码为 $13+127=140=[10001100]$，加上符号位的 $0$，就得到浮点表示 $[0\ 10001100\ 10000001110010000000000]$.

***

浮点数的舍入：向偶数舍入。“正中间”的值（也就是形如 $Y100\ldots$ 的值，$Y$ 为要舍入到的位）向偶数（$Y=0$ 时去尾，$Y=1$ 时进位）舍入，不是“正中间”的值向最接近的数舍入。例如将一下数字舍入到最接近的二分之一：

- $10.010_2 : 10.0$
- $10.011_2 : 10.1$
- $10.110_2 : 11.0$
- $11.001_2 : 11.0$

***

浮点加法和乘法：可交换，但**不可结合**，乘法对加法**没有分配律**。

浮点加法**有单调性**：若 $a \geq b$ 且 $a, b, x \neq NaN$，则 $x+a\geq x+b$. 乘法同理.

***

在 C 语言中：

- `int` -> `float`：不会溢出，可能被舍入（向 0 舍入）
- `int` 或 `float` -> `double`：保留精确的数值
- `double` -> `float`：可能溢出成 $+\infin$ 或 $-\infin$，也可能被舍入
- `float` 或 `double` -> `int`：向 0 舍入，可能会溢出（此时的值标准未指定，Intel 指定了**整数不确定**值 $\text{TMin}_\omega$）
